/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.karuppiah7890.kafkaprotobufproducer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KafkaProtobufProducerAppTest {

}
