/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.karuppiah7890.kafkaprotobufproducer;

public class KafkaProtobufProducerApp {

    public static void main(String[] args) {

    }
}
